import fp from "fastify-plugin";
import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { randomBytes, timingSafeEqual, createPrivateKey, sign } from "crypto";
import { existsSync, readFileSync, writeFileSync } from "fs";
import { getConfig } from "./autonomy/optimizer.js";
import { checkSubscription, incrementUsage } from "./stripe-subscriptions.js";
import { getCredits, deductCredits } from "./stripe-credits.js";
import { sendEmail, hashIp, lookupEmailByIpHash, buildPaymentRecoveryEmail, isMailerEnabled } from "./mailer.js";

const PAY_TO = "0x8D76E8FB38541d70dF74b14660c39b4c5d737088";
const USDC = "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913";
const NETWORK = "base" as const;
const PAYMENTS_LEDGER = "/agent/data/payments.json";

/**
 * Shared x402 correct-format guidance block.
 * Included in ALL 402 responses so AI agents immediately understand the protocol.
 */
const X402_FORMAT_GUIDE = {
  description: "Pay per-request with USDC on Base — no subscription needed",
  docs: "https://anybrowse.dev/docs/x402",
  quickstart: "npm install x402 && use wrapFetch from 'x402/client'",
  correct_format: {
    header_name: "X-PAYMENT",
    header_value: "base64(JSON payload — generated by x402 client library)",
    json_structure: {
      x402Version: 1,
      scheme: "exact",
      network: "base-mainnet",
      payload: { "...": "use x402 client library to generate this — do NOT construct manually" },
    },
    warning: "Do NOT manually construct this header. Use: import { wrapFetch } from 'x402/client'",
    example: {
      step1: "npm install x402",
      step2: "import { wrapFetch } from 'x402/client'",
      step3: "const fetch402 = wrapFetch(fetch, wallet)",
      step4: "await fetch402('https://anybrowse.dev/scrape', { method: 'POST', body: JSON.stringify({url}) })",
    },
  },
};

// CDP Facilitator (Coinbase-hosted, production) or fallback to self-hosted
const CDP_FACILITATOR_URL = "https://api.cdp.coinbase.com/platform/v2/x402";
const SELF_HOSTED_FACILITATOR_URL = "http://127.0.0.1:8080";
const FACILITATOR_URL = process.env.FACILITATOR_URL || CDP_FACILITATOR_URL;
const PUBLIC_FACILITATOR = FACILITATOR_URL === SELF_HOSTED_FACILITATOR_URL
  ? "https://anybrowse.dev/facilitator"
  : CDP_FACILITATOR_URL;

const DEFAULT_PRICES: Record<string, number> = {
  "/scrape": 2000,
  "/crawl": 10000,
  "/serp/search": 2000,
  "/extract": 10000,
};

const USDC_EIP712 = {
  name: "USD Coin",
  version: "2",
  chainId: 8453,
  verifyingContract: USDC,
};

// Internal bypass token — regenerated every startup, used by MCP handler
const INTERNAL_BYPASS_TOKEN = randomBytes(32).toString("hex");
const BYPASS_TOKEN_BUF = Buffer.from(INTERNAL_BYPASS_TOKEN, "hex");

export function validateInternalToken(candidate: string): boolean {
  try {
    const candidateBuf = Buffer.from(candidate, "hex");
    if (candidateBuf.length !== BYPASS_TOKEN_BUF.length) return false;
    return timingSafeEqual(candidateBuf, BYPASS_TOKEN_BUF);
  } catch {
    return false;
  }
}

export function getInternalToken(): string {
  return INTERNAL_BYPASS_TOKEN;
}

// ── Free tier rate limiting (50 scrapes/day per IP for direct API) ──────────
// MCP endpoint (/mcp) is handled separately and is UNLIMITED for agents.
const FREE_TIER_DAILY_LIMIT = 50;
const FREE_TIER_DAY_MS = 86_400_000; // 24h in ms

interface FreeTierEntry {
  count: number;
  resetAt: number; // epoch ms
}

const freeTierMap = new Map<string, FreeTierEntry>();

// Midnight UTC reset cleanup
setInterval(() => {
  const now = Date.now();
  for (const [ip, entry] of freeTierMap) {
    if (now >= entry.resetAt) freeTierMap.delete(ip);
  }
}, 60_000);

/**
 * Get next midnight UTC as epoch ms
 */
function nextMidnightUtc(): number {
  const now = new Date();
  const midnight = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate() + 1));
  return midnight.getTime();
}

/**
 * Check (and consume) a free-tier slot for the given IP.
 * Returns { allowed: true } if under limit, or { allowed: false } when exhausted.
 */
function checkFreeTier(ip: string): { allowed: boolean } {
  const now = Date.now();
  let entry = freeTierMap.get(ip);

  if (!entry || now >= entry.resetAt) {
    entry = { count: 0, resetAt: nextMidnightUtc() };
    freeTierMap.set(ip, entry);
  }

  if (entry.count >= FREE_TIER_DAILY_LIMIT) {
    return { allowed: false };
  }

  entry.count++;
  return { allowed: true };
}

// Payment replay protection
const SETTLED_PAYMENTS = new Set<string>();

function getPaymentHash(payment: any): string {
  return Buffer.from(JSON.stringify(payment)).toString("base64").slice(0, 64);
}

setInterval(() => {
  if (SETTLED_PAYMENTS.size > 1000) {
    SETTLED_PAYMENTS.clear();
  }
}, 5 * 60 * 1000);

interface PaymentEvent {
  timestamp: string;
  endpoint: string;
  payer: string;
  amountMicro: number;
  amountUSDC: string;
  transaction: string | null;
  status: "settled" | "settlement_failed";
  error?: string;
}

function recordPayment(event: PaymentEvent): void {
  try {
    let ledger: PaymentEvent[] = [];
    if (existsSync(PAYMENTS_LEDGER)) {
      ledger = JSON.parse(readFileSync(PAYMENTS_LEDGER, "utf-8"));
    }
    ledger.push(event);
    if (ledger.length > 10000) {
      ledger = ledger.slice(-10000);
    }
    writeFileSync(PAYMENTS_LEDGER, JSON.stringify(ledger, null, 2));
  } catch (err: any) {
    console.error("[payment-gate] Failed to persist payment event:", err.message);
  }
}

function isValidBypassToken(candidate: string | undefined): boolean {
  if (!candidate) return false;
  // Owner API key — full bypass, no rate limits, no payment checks
  const ownerKey = process.env.OWNER_API_KEY;
  if (ownerKey && candidate === ownerKey) return true;
  return validateInternalToken(candidate);
}

export function isOwnerKey(candidate: string | undefined): boolean {
  if (!candidate) return false;
  const ownerKey = process.env.OWNER_API_KEY;
  return !!(ownerKey && candidate === ownerKey);
}

/**
 * Generate a CDP JWT for a specific API action.
 * Uses Ed25519 signing (EdDSA) — replaces @coinbase/cdp-sdk/auth to avoid
 * its ESM "Octal escape sequences" bug in Node 22 + pm2.
 */
function generateCdpJwt(
  keyId: string,
  privateKey: ReturnType<typeof createPrivateKey>,
  method: string,
  path: string,
): string {
  const now = Math.floor(Date.now() / 1000);

  const header = {
    alg: "EdDSA",
    kid: keyId,
    typ: "JWT",
    nonce: randomBytes(16).toString("hex"),
  };

  const payload = {
    sub: keyId,
    iss: "cdp",
    aud: ["cdp_service"],
    nbf: now,
    exp: now + 120,
    uris: [`${method} api.cdp.coinbase.com${path}`],
  };

  const headerB64 = Buffer.from(JSON.stringify(header)).toString("base64url");
  const payloadB64 = Buffer.from(JSON.stringify(payload)).toString("base64url");
  const signingInput = `${headerB64}.${payloadB64}`;

  const signature = sign(null, Buffer.from(signingInput), privateKey);
  return `${signingInput}.${signature.toString("base64url")}`;
}

/**
 * Build a createAuthHeaders callback for HTTPFacilitatorClient.
 * Returns undefined if CDP keys are not configured.
 */
function createCdpAuthHeadersFn(): (() => Promise<{ verify: Record<string, string>; settle: Record<string, string>; supported: Record<string, string> }>) | undefined {
  const keyId = process.env.CDP_API_KEY_ID;
  const keySecret = process.env.CDP_API_KEY_SECRET;
  if (!keyId || !keySecret) return undefined;

  // Decode the Ed25519 private key (64 bytes: 32-byte seed + 32-byte public)
  let privateKey: ReturnType<typeof createPrivateKey>;
  try {
    const rawKey = Buffer.from(keySecret, "base64");
    const seed = rawKey.subarray(0, 32);
    // Wrap in PKCS8 DER envelope for Ed25519
    const pkcs8Header = Buffer.from("302e020100300506032b657004220420", "hex");
    const pkcs8Der = Buffer.concat([pkcs8Header, seed]);
    privateKey = createPrivateKey({ key: pkcs8Der, format: "der", type: "pkcs8" });
    console.log("[payment-gate] CDP Ed25519 key loaded successfully");
  } catch (err: any) {
    console.error("[payment-gate] Failed to load CDP key:", err.message);
    return undefined;
  }

  return async () => ({
    verify:    { Authorization: `Bearer ${generateCdpJwt(keyId, privateKey, "POST", "/platform/v2/x402/verify")}` },
    settle:    { Authorization: `Bearer ${generateCdpJwt(keyId, privateKey, "POST", "/platform/v2/x402/settle")}` },
    supported: { Authorization: `Bearer ${generateCdpJwt(keyId, privateKey, "GET",  "/platform/v2/x402/supported")}` },
  });
}


function isAgentRequest(req: FastifyRequest): boolean {
  const ua = req.headers['user-agent'] || '';
  const referer = req.headers['referer'] || '';
  return (
    ua.includes('Claude') || ua.includes('Cursor') || ua.includes('Windsurf') ||
    ua.toLowerCase().includes('python') || ua.toLowerCase().includes('urllib') || ua.toLowerCase().includes('httpx') ||
    ua.includes('node-fetch') || ua.includes('axios') ||
    ua.includes('okhttp') || ua.includes('Go-http') ||
    (!referer && !ua.includes('Mozilla')) // no referer + not a browser = likely agent
  );
}

export default fp(async function paymentGate(app: FastifyInstance) {
  let facilitatorUrl = FACILITATOR_URL;
  let publicFacilitator = PUBLIC_FACILITATOR;

  // Try CDP facilitator first, fall back to self-hosted
  const cdpAuthFn = createCdpAuthHeadersFn();
  const useCdp = cdpAuthFn && facilitatorUrl === CDP_FACILITATOR_URL;

  if (useCdp) {
    console.log("[payment-gate] Using CDP facilitator (Coinbase-hosted)");
  } else if (facilitatorUrl === CDP_FACILITATOR_URL && !cdpAuthFn) {
    // CDP keys not set or key load failed, fall back to self-hosted
    facilitatorUrl = SELF_HOSTED_FACILITATOR_URL;
    publicFacilitator = "https://anybrowse.dev/facilitator";
    console.log("[payment-gate] CDP keys not configured, falling back to self-hosted facilitator");
  }

  // Use @x402/core HTTPFacilitatorClient for CDP, else old x402 package for self-hosted
  let facilitator: { verify: Function; settle: Function };

  if (useCdp) {
    const { HTTPFacilitatorClient } = await import("@x402/core/server");
    const client = new HTTPFacilitatorClient({
      url: facilitatorUrl,
      createAuthHeaders: cdpAuthFn,
    });
    facilitator = client;
    console.log(`[payment-gate] CDP facilitator: ${facilitatorUrl}`);
  } else {
    const { useFacilitator } = await import("x402/verify");
    facilitator = useFacilitator({
      url: facilitatorUrl as `${string}://${string}`,
    });
    console.log(`[payment-gate] Self-hosted facilitator: ${facilitatorUrl}`);
  }

  console.log(`[payment-gate] Public facilitator:   ${publicFacilitator}`);
  console.log(`[payment-gate] Payment ledger:       ${PAYMENTS_LEDGER}`);

  function getCurrentPrice(path: string): number | undefined {
    const config = getConfig();
    const configPrices: Record<string, number> = {
      "/scrape": config.pricing.scrape,
      "/crawl": config.pricing.crawl,
      "/extract": config.pricing.crawl, // same as crawl
      "/serp/search": config.pricing.search,
    };
    return configPrices[path] ?? DEFAULT_PRICES[path];
  }

  function buildPaymentRequirements(path: string, method: string, amount: number) {
    return {
      scheme: "exact" as const,
      network: NETWORK,
      maxAmountRequired: String(amount),
      resource: `https://anybrowse.dev${path}`,
      description:
        "anybrowse — autonomous web browsing agent. LLM-optimized Markdown.",
      mimeType: "application/json",
      payTo: PAY_TO,
      maxTimeoutSeconds: 300,
      asset: USDC,
      outputSchema: {
        input: { type: "http", method, discoverable: true },
      },
      extra: USDC_EIP712,
    };
  }

  app.addHook(
    "preHandler",
    async (req: FastifyRequest, reply: FastifyReply) => {
      const path = req.url.split("?")[0];
      if (isValidBypassToken(req.headers["x-internal-token"] as string)) return;

      // Owner API key via Authorization: Bearer or X-API-Key
      const ownerAuthHeader = (req.headers["authorization"] as string) || "";
      const ownerApiKeyHeader = (req.headers["x-api-key"] as string) || "";
      const ownerBearer = ownerAuthHeader.startsWith("Bearer ") ? ownerAuthHeader.slice(7) : ownerAuthHeader;
      if (isOwnerKey(ownerBearer || ownerApiKeyHeader)) return;

      const amount = getCurrentPrice(path);
      if (!amount) return;

      // ── Stripe Pro subscription check ──────────────────────────────
      // Accept: Authorization: Bearer ab_xxxx  or  X-API-Key: ab_xxxx
      const authHeader = req.headers["authorization"] as string | undefined;
      const apiKeyHeader = req.headers["x-api-key"] as string | undefined;
      let stripeApiKey: string | undefined;
      if (authHeader?.startsWith("Bearer ab_")) {
        stripeApiKey = authHeader.slice(7).trim();
      } else if (apiKeyHeader?.startsWith("ab_")) {
        stripeApiKey = apiKeyHeader.trim();
      }

      if (stripeApiKey) {
        const check = checkSubscription(stripeApiKey);
        if (check.valid && check.record) {
          // Valid Pro subscriber — let them through and count usage
          (req as any).stripeApiKey = stripeApiKey;
          incrementUsage(stripeApiKey);
          return; // ← skip x402 check
        } else if (check.reason === "API key not found") {
          // Not a subscription key — check if it's a credit-pack key
          const credits = getCredits(stripeApiKey);
          if (credits > 0) {
            // Valid credit-pack key with credits remaining
            (req as any).creditKey = stripeApiKey;
            return; // ← allow through; credits deducted in onSend
          } else if (credits === 0) {
            // Credit key found but exhausted
            reply.status(402).send({
              error: "No credits remaining. Top up at https://anybrowse.dev/credits",
              upgrade: "https://anybrowse.dev/credits",
              credits: 0,
            });
            return;
          } else {
            // Key not found at all — fall through to x402/free tier
            reply.status(402).send({
              error: `Pro subscription invalid: ${check.reason}`,
              upgrade: "https://anybrowse.dev/checkout",
              credit_packs: "https://anybrowse.dev/credits",
              reset: "Contact support or resubscribe",
              pro: "$4.99/month for 10,000 scrapes",
            });
            return;
          }
        } else {
          // Key present but invalid/over-limit subscription
          reply.status(402).send({
            error: `Pro subscription invalid: ${check.reason}`,
            upgrade: "https://anybrowse.dev/checkout",
            credit_packs: "https://anybrowse.dev/credits",
            reset: "Contact support or resubscribe",
            pro: "$4.99/month for 10,000 scrapes",
          });
          return;
        }
      }
      // ── end Stripe check ───────────────────────────────────────────

      // ── end Stripe / free tier gate ───────────────────────────────
      const xPayment = req.headers["x-payment"] as string | undefined;

      // If no x402 payment header is present, apply free tier (10/day per IP)
      if (!xPayment) {
        const clientIp = req.ip || "unknown";
        const freeTierOk = checkFreeTier(clientIp);
        if (!freeTierOk.allowed) {
          const agentReq = isAgentRequest(req);
          if (agentReq) {
            // Developer/agent hitting limit via direct API call
            reply.status(402).send({
              error: "Daily free limit reached (50 scrapes/day for direct API). Use the MCP endpoint for unlimited agent access.",
              mcp_endpoint: "https://anybrowse.dev/mcp",
              upgrade: "https://anybrowse.dev/checkout",
              reset: "Resets at midnight UTC",
              pro: "$4.99/month for 10,000 scrapes",
              notify_me: "POST your email to https://anybrowse.dev/capture-email to get notified about Pro deals",
              x402: X402_FORMAT_GUIDE,
              accepts: [buildPaymentRequirements(path, req.method, amount)],
            });
          } else {
            // Human browser - encourage email capture on the landing page
            reply.status(402).send({
              error: "Daily free limit reached (50 scrapes/day)",
              upgrade: "https://anybrowse.dev/checkout",
              reset: "Resets at midnight UTC",
              pro: "$4.99/month for 10,000 scrapes",
              capture_email: true,
              capture_url: "https://anybrowse.dev",
              x402: X402_FORMAT_GUIDE,
              accepts: [buildPaymentRequirements(path, req.method, amount)],
            });
          }
          return;
        }
        // Free tier slot consumed — allow request through, skip x402
        return;
      }
      // ── x402 payment path ─────────────────────────────────────────

      const paymentRequirements = buildPaymentRequirements(path, req.method, amount);

      let decodedPayment: any;
      try {
        const decoded = Buffer.from(xPayment, "base64").toString("utf-8");
        decodedPayment = JSON.parse(decoded);
      } catch {
        reply.status(402).send({
          x402Version: 1,
          error: "Invalid X-PAYMENT header — expected base64 JSON",
          accepts: [paymentRequirements],
          facilitator: publicFacilitator,
          docs: "https://anybrowse.dev/docs/x402",
          hint: "Do not manually construct the X-PAYMENT header. Use the x402 client library (npm install x402) or Coinbase AgentKit — they handle encoding automatically.",
          x402: X402_FORMAT_GUIDE,
        });
        return;
      }

      const paymentHash = getPaymentHash(decodedPayment);
      if (SETTLED_PAYMENTS.has(paymentHash)) {
        console.log(`[payment-gate] Replay rejected: ${paymentHash.slice(0, 16)}...`);
        reply.status(402).send({
          x402Version: 1,
          error: "Payment already used",
          accepts: [paymentRequirements],
          facilitator: publicFacilitator,
        });
        return;
      }

      try {
        const verifyResult = await facilitator.verify(decodedPayment, paymentRequirements);
        if (!verifyResult.isValid) {
          const failReason = verifyResult.invalidReason ?? "unknown";
          console.log(`[payment-gate] Verification failed: ${failReason}`);
          reply.status(402).send({
            x402Version: 1,
            error: `Payment verification failed: ${failReason}`,
            accepts: [paymentRequirements],
            facilitator: publicFacilitator,
            docs: "https://anybrowse.dev/docs/x402",
            hint: "Your X-PAYMENT header must be a base64-encoded JSON payload. Use the x402 client library or Coinbase AgentKit. See docs for a working example.",
            x402: X402_FORMAT_GUIDE,
          });

          // Task 5: fire recovery email if we have this IP's email on file
          if (isMailerEnabled()) {
            const clientIp = (req.headers["x-forwarded-for"] as string)?.split(",")[0]?.trim() || req.ip || "unknown";
            const ipHash = hashIp(clientIp);
            const recipientEmail = lookupEmailByIpHash(ipHash);
            if (recipientEmail) {
              const { subject, text, html } = buildPaymentRecoveryEmail(failReason);
              sendEmail({ to: recipientEmail, subject, text, html }).catch((err) => {
                console.error(`[payment-gate] Recovery email failed for ${recipientEmail}:`, err.message);
              });
              console.log(`[payment-gate] Recovery email queued → ${recipientEmail} (ip_hash=${ipHash})`);
            } else {
              console.log(`[payment-gate] No email on file for ip_hash=${ipHash} — skipping recovery email`);
            }
          }
          return;
        }
        console.log(`[payment-gate] Payment verified from ${verifyResult.payer}`);
      } catch (err: any) {
        console.error(`[payment-gate] Verify error:`, err.message || err);
        reply.status(402).send({
          x402Version: 1,
          error: "Payment verification error — try again",
          accepts: [paymentRequirements],
          facilitator: publicFacilitator,
        });
        return;
      }

      (req as any).x402Payment = decodedPayment;
      (req as any).x402Requirements = paymentRequirements;
      (req as any).x402PaymentHash = paymentHash;
    },
  );

  app.addHook(
    "onSend",
    async (req: FastifyRequest, reply: FastifyReply, payload: unknown) => {
      // ── Credit pack deduction ─────────────────────────────────────
      const creditKey = (req as any).creditKey as string | undefined;
      if (creditKey && reply.statusCode < 400) {
        const path = req.url.split("?")[0];
        // Determine credit cost by endpoint
        let creditCost = 1; // default: 1 credit per /scrape
        if (path === "/crawl" || path === "/extract") creditCost = 5;
        else if (path === "/serp/search") creditCost = 1;
        else if (path === "/batch") {
          // For batch, count URLs in the request body
          const body = req.body as any;
          const urlCount = Array.isArray(body?.urls) ? body.urls.length : 1;
          creditCost = urlCount;
        }
        const success = deductCredits(creditKey, creditCost);
        if (!success) {
          console.warn(`[payment-gate] Credit deduction failed for ${creditKey.slice(0, 12)}... — insufficient credits`);
        } else {
          console.log(`[payment-gate] Deducted ${creditCost} credit(s) from ${creditKey.slice(0, 12)}...`);
        }
      }

      const decodedPayment = (req as any).x402Payment;
      const paymentRequirements = (req as any).x402Requirements;
      const paymentHash = (req as any).x402PaymentHash as string | undefined;
      if (!decodedPayment || !paymentRequirements) return payload;

      const path = req.url.split("?")[0];
      const amount = getCurrentPrice(path) || 0;

      if (reply.statusCode >= 400) {
        console.log(`[payment-gate] Skipping settlement — response ${reply.statusCode}`);
        return payload;
      }

      try {
        const settleResult = await facilitator.settle(decodedPayment, paymentRequirements);
        if (!settleResult.success) {
          console.error(`[payment-gate] Settlement failed: ${settleResult.errorReason}`);
          recordPayment({
            timestamp: new Date().toISOString(),
            endpoint: path,
            payer: settleResult.payer || "unknown",
            amountMicro: amount,
            amountUSDC: (amount / 1_000_000).toFixed(6),
            transaction: null,
            status: "settlement_failed",
            error: settleResult.errorReason,
          });
          reply.status(402);
          return JSON.stringify({
            x402Version: 1,
            error: `Payment settlement failed: ${settleResult.errorReason}`,
          });
        }

        console.log(`[payment-gate] Settled! tx=${settleResult.transaction} payer=${settleResult.payer}`);
        if (paymentHash) SETTLED_PAYMENTS.add(paymentHash);

        recordPayment({
          timestamp: new Date().toISOString(),
          endpoint: path,
          payer: settleResult.payer || "unknown",
          amountMicro: amount,
          amountUSDC: (amount / 1_000_000).toFixed(6),
          transaction: settleResult.transaction,
          status: "settled",
        });

        const proof = Buffer.from(JSON.stringify(settleResult)).toString("base64");
        reply.header("X-PAYMENT-RESPONSE", proof);
      } catch (err: any) {
        console.error(`[payment-gate] Settle error:`, err.message || err);
        recordPayment({
          timestamp: new Date().toISOString(),
          endpoint: path,
          payer: "unknown",
          amountMicro: amount,
          amountUSDC: (amount / 1_000_000).toFixed(6),
          transaction: null,
          status: "settlement_failed",
          error: err.message || String(err),
        });
        reply.status(402);
        return JSON.stringify({ x402Version: 1, error: "Payment settlement error" });
      }

      return payload;
    },
  );
});
